export * from './completed-tasks-detail-page/completed-tasks-detail-page.component';
export * from './completed-tasks-page/completed-tasks-page.component';
export * from './current-task-detail-edit-page/current-task-detail-edit-page.component';
export * from './current-tasks-page/current-tasks-page.component';
export * from './current-task-detail-new-page/current-task-detail-new-page.component';
export * from './task-list-detail-edit-page/task-list-detail-edit-page.component';
export * from './task-list-detail-new-page/task-list-detail-new-page.component';
export * from './task-lists-page/task-lists-page.component';
export * from './current-task-detail-edit-page/current-task-detail-edit-page.component';
